/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.50
 * Generated at: 2022-04-29 16:09:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user.gioi_002dthieu;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class gioi_002dthieu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<div id=\"content\" class=\"site-content\" tabindex=\"-1\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("		<nav class=\"woocommerce-breadcrumb\"><a href=\"https://ldstore.vn\">Trang chủ</a><span class=\"delimiter\"><i class=\"fa fa-angle-right\"></i></span>Giới thiệu về LD Store</nav><div class=\"site-content-inner row\">\r\n");
      out.write("<div id=\"primary\" class=\"content-area\">\r\n");
      out.write("	<main id=\"main\" class=\"site-main\">\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("<article id=\"post-47138\" class=\"post-47138 page type-page status-publish hentry\">\r\n");
      out.write("\r\n");
      out.write("					<header class=\"entry-header\">\r\n");
      out.write("					<h1 class=\"entry-title\">Giới thiệu về LD Store</h1>\r\n");
      out.write("									</header><!-- .entry-header -->\r\n");
      out.write("						<div class=\"entry-content\">\r\n");
      out.write("			<div class=\"vc_row wpb_row vc_row-fluid\"><div class=\"wpb_column vc_column_container vc_col-sm-6\"><div class=\"vc_column-inner\"><div class=\"wpb_wrapper\">\r\n");
      out.write("	<div class=\"wpb_text_column wpb_content_element \">\r\n");
      out.write("		<div class=\"wpb_wrapper\">\r\n");
      out.write("			<p><img class=\"alignleft wp-image-47114 size-full\" src=\"https://ldstore.vn/devup/wp-content/uploads/2021/05/ld-store-logo-bluemind.png\" alt=\"\" width=\"280\" srcset=\"https://ldstore.vn/wp-content/uploads/2021/05/ld-store-logo-bluemind.png 447w, https://ldstore.vn/wp-content/uploads/2021/05/ld-store-logo-bluemind-300x91.png 300w\" sizes=\"(max-width: 447px) 100vw, 447px\"></p>\r\n");
      out.write("<p><strong>Cửa hàng tại Hà Nội:</strong> Số 157 Trần Quốc Hoàn , Cầu Giấy , Hà Nội. – <a href=\"tel:+84924049999\">0924049999</a><br>\r\n");
      out.write("<strong>Cửa hàng tại Hồ Chí Minh:</strong> Đang cập nhật … – <a href=\"tel:0947022222\">0947022222</a><br>\r\n");
      out.write("<strong>Cửa hàng tại Đắk Lắk:</strong> Số 195 Lê Duẩn TP. Buôn Ma Thuột , Đắk Lắk <a href=\"tel:0947022222\">0947022222</a><br>\r\n");
      out.write("Email: <a title=\"ldstorevn8@gmail.com\" href=\"mailto:ldstorevn8@gmail.com\">ldstorevn8@gmail.com</a><br>\r\n");
      out.write("Giấy chứng nhận ĐKKD số 01G8021941 do UBND Quận Cầu Giấy – Hà Nội cấp ngày 04/01/2018</p>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div></div></div><div class=\"wpb_column vc_column_container vc_col-sm-6\"><div class=\"vc_column-inner\"><div class=\"wpb_wrapper\">\r\n");
      out.write("	<div class=\"wpb_text_column wpb_content_element \">\r\n");
      out.write("		<div class=\"wpb_wrapper\">\r\n");
      out.write("			<p>LD STORE là Shop chuyên đồng hồ thông minh SmartWatch đầu tiên Việt Nam. Tuổi đời hoạt động 5 năm với nhiều kinh nghiệm tư vấn chia sẻ khách hàng.</p>\r\n");
      out.write("<p>Hiện tại LD STORE nhóm cộng đồng về SmartWatch lớn nhất tại Việt Nam trên Facebook : <a href=\"https://www.facebook.com/groups/smartwachvietnam/\" class=\"external\" rel=\"nofollow\" target=\"_blank\">Hội SmartWatch Việt Nam</a>&nbsp;và Fanpage SmartWatch Việt Nam.</p>\r\n");
      out.write("<p>Và phát triển Kênh Youtube “Lâm SmartWatch” quản lí chính của Shop với lượng fan và lượt xem nhiều từ chia sẻ kinh nghiệm đánh giá.</p>\r\n");
      out.write("<p>LD STORE sẽ luôn không ngừng phát triển với uy tín sẵn có từ cộng đồng và quý khách hàng !!!</p>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div></div></div></div>\r\n");
      out.write("		</div><!-- .entry-content -->\r\n");
      out.write("			\r\n");
      out.write("</article><!-- #post-## -->\r\n");
      out.write("\r\n");
      out.write("	</main><!-- #main -->\r\n");
      out.write("</div><!-- #primary -->\r\n");
      out.write("\r\n");
      out.write("			</div>		</div><!-- .col-full -->\r\n");
      out.write("	</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
